package main

import (
	"fmt"
)

/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

https://projecteuler.net/problem=2

*/

func main() {
    first := 1
    second := 2
    fib := first + second
    sum := 0
    for fib < 4000000 {
        if fib % 2 == 0 {
            sum += fib
        }
        first = second
        second = fib
	fib = first + second
    }
    fmt.Println(sum + 2)
}
